# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KontaktmanagerMLuNmn.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCalendarWidget, QCheckBox,
    QDockWidget, QHeaderView, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QTableView, QToolBar, QToolBox,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1493, 929)
        MainWindow.setMinimumSize(QSize(1493, 929))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        self.actionDatenbank = QAction(MainWindow)
        self.actionDatenbank.setObjectName(u"actionDatenbank")
        self.actionDanebank_l_schen = QAction(MainWindow)
        self.actionDanebank_l_schen.setObjectName(u"actionDanebank_l_schen")
        self.actionBeenden = QAction(MainWindow)
        self.actionBeenden.setObjectName(u"actionBeenden")
        self.actionKontakte = QAction(MainWindow)
        self.actionKontakte.setObjectName(u"actionKontakte")
        self.actionKontakte_bearbeiten = QAction(MainWindow)
        self.actionKontakte_bearbeiten.setObjectName(u"actionKontakte_bearbeiten")
        self.actionKontakte_l_schen = QAction(MainWindow)
        self.actionKontakte_l_schen.setObjectName(u"actionKontakte_l_schen")
        self.actionGlobale_Einstellungen = QAction(MainWindow)
        self.actionGlobale_Einstellungen.setObjectName(u"actionGlobale_Einstellungen")
        self.actionTAGs_Verwalten = QAction(MainWindow)
        self.actionTAGs_Verwalten.setObjectName(u"actionTAGs_Verwalten")
        self.actionGruppen_Verwalten = QAction(MainWindow)
        self.actionGruppen_Verwalten.setObjectName(u"actionGruppen_Verwalten")
        self.actionHilfe = QAction(MainWindow)
        self.actionHilfe.setObjectName(u"actionHilfe")
        self.actionKontakt_hinzuf_gen = QAction(MainWindow)
        self.actionKontakt_hinzuf_gen.setObjectName(u"actionKontakt_hinzuf_gen")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.calendarWidget = QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(10, 410, 811, 461))
        self.calendarWidget.setMouseTracking(True)
        self.calendarWidget.setTabletTracking(True)
        self.calendarWidget.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.calendarWidget.setAcceptDrops(True)
        self.calendarWidget.setGridVisible(True)
        self.tableViewKontakteliste = QTableView(self.centralwidget)
        self.tableViewKontakteliste.setObjectName(u"tableViewKontakteliste")
        self.tableViewKontakteliste.setGeometry(QRect(840, 440, 371, 431))
        self.tableViewKontakteliste.setAcceptDrops(True)
        self.tableViewKontakteliste.setAutoFillBackground(True)
        self.tableViewKontakteliste.setDragDropMode(QAbstractItemView.DragDrop)
        self.plainTextEditkontaktsuche = QPlainTextEdit(self.centralwidget)
        self.plainTextEditkontaktsuche.setObjectName(u"plainTextEditkontaktsuche")
        self.plainTextEditkontaktsuche.setGeometry(QRect(840, 350, 341, 21))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(840, 380, 181, 23))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(1030, 380, 181, 23))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(840, 410, 361, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1493, 21))
        self.menuDatei = QMenu(self.menubar)
        self.menuDatei.setObjectName(u"menuDatei")
        self.menuBearbeiten = QMenu(self.menubar)
        self.menuBearbeiten.setObjectName(u"menuBearbeiten")
        self.menuEinstellungen = QMenu(self.menubar)
        self.menuEinstellungen.setObjectName(u"menuEinstellungen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.MENU = QToolBox(self.dockWidgetContents)
        self.MENU.setObjectName(u"MENU")
        self.Einstellungenglobal = QWidget()
        self.Einstellungenglobal.setObjectName(u"Einstellungenglobal")
        self.Einstellungenglobal.setGeometry(QRect(0, 0, 214, 728))
        self.checkBox = QCheckBox(self.Einstellungenglobal)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 0, 141, 20))
        self.checkBox_2 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 20, 151, 20))
        self.checkBox_3 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(10, 40, 151, 20))
        self.checkBox_4 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(10, 60, 151, 20))
        self.checkBox_5 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(10, 80, 151, 20))
        self.checkBox_6 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 100, 151, 20))
        self.checkBox_7 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 120, 151, 20))
        self.checkBox_8 = QCheckBox(self.Einstellungenglobal)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(10, 140, 151, 20))
        self.MENU.addItem(self.Einstellungenglobal, u"Einstellungenglobal")
        self.Kontakte = QWidget()
        self.Kontakte.setObjectName(u"Kontakte")
        self.Kontakte.setEnabled(True)
        self.Kontakte.setGeometry(QRect(0, 0, 214, 728))
        self.Kontakte.setToolTipDuration(2)
        self.pushButton = QPushButton(self.Kontakte)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 0, 181, 23))
        self.pushButton_2 = QPushButton(self.Kontakte)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 30, 181, 23))
        self.pushButton_3 = QPushButton(self.Kontakte)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(0, 60, 181, 23))
        self.MENU.addItem(self.Kontakte, u"Kontakte")
        self.TAGs = QWidget()
        self.TAGs.setObjectName(u"TAGs")
        self.TAGs.setGeometry(QRect(0, 0, 214, 728))
        self.TAGs.setInputMethodHints(Qt.ImhNone)
        self.widget = QWidget(self.TAGs)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 183, 721))
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton_12 = QPushButton(self.widget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setMaximumSize(QSize(181, 21))

        self.verticalLayout_2.addWidget(self.pushButton_12)

        self.pushButton_10 = QPushButton(self.widget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setMaximumSize(QSize(181, 23))

        self.verticalLayout_2.addWidget(self.pushButton_10)

        self.pushButton_11 = QPushButton(self.widget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setMaximumSize(QSize(181, 23))

        self.verticalLayout_2.addWidget(self.pushButton_11)

        self.tableViewTAG = QTableView(self.widget)
        self.tableViewTAG.setObjectName(u"tableViewTAG")
        self.tableViewTAG.setMaximumSize(QSize(181, 650))

        self.verticalLayout_2.addWidget(self.tableViewTAG)

        self.MENU.addItem(self.TAGs, u"TAG's")
        self.Gruppen = QWidget()
        self.Gruppen.setObjectName(u"Gruppen")
        self.Gruppen.setGeometry(QRect(0, 0, 214, 728))
        self.widget1 = QWidget(self.Gruppen)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(0, 4, 183, 681))
        self.verticalLayout_3 = QVBoxLayout(self.widget1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pushButton_14 = QPushButton(self.widget1)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setMaximumSize(QSize(181, 21))

        self.verticalLayout_3.addWidget(self.pushButton_14)

        self.pushButton_13 = QPushButton(self.widget1)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setMaximumSize(QSize(181, 23))

        self.verticalLayout_3.addWidget(self.pushButton_13)

        self.pushButton_15 = QPushButton(self.widget1)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setMaximumSize(QSize(181, 23))

        self.verticalLayout_3.addWidget(self.pushButton_15)

        self.tableViewTAG_2 = QTableView(self.widget1)
        self.tableViewTAG_2.setObjectName(u"tableViewTAG_2")
        self.tableViewTAG_2.setMaximumSize(QSize(181, 650))

        self.verticalLayout_3.addWidget(self.tableViewTAG_2)

        self.MENU.addItem(self.Gruppen, u"Gruppen")

        self.verticalLayout.addWidget(self.MENU)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())
        self.menubar.addAction(self.menuEinstellungen.menuAction())
        self.menuDatei.addAction(self.actionDatenbank)
        self.menuDatei.addAction(self.actionDanebank_l_schen)
        self.menuDatei.addAction(self.actionBeenden)
        self.menuBearbeiten.addAction(self.actionKontakte)
        self.menuBearbeiten.addAction(self.actionKontakte_bearbeiten)
        self.menuBearbeiten.addAction(self.actionKontakte_l_schen)
        self.menuEinstellungen.addAction(self.actionGlobale_Einstellungen)
        self.menuEinstellungen.addAction(self.actionTAGs_Verwalten)
        self.menuEinstellungen.addAction(self.actionGruppen_Verwalten)
        self.menuEinstellungen.addAction(self.actionHilfe)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDatenbank.setText(QCoreApplication.translate("MainWindow", u"Datenbank Aktualisieren", None))
        self.actionDanebank_l_schen.setText(QCoreApplication.translate("MainWindow", u"Danebank l\u00f6schen", None))
        self.actionBeenden.setText(QCoreApplication.translate("MainWindow", u"Beenden", None))
        self.actionKontakte.setText(QCoreApplication.translate("MainWindow", u"Kontakte hinzuf\u00fcgen", None))
        self.actionKontakte_bearbeiten.setText(QCoreApplication.translate("MainWindow", u"Kontakte bearbeiten", None))
        self.actionKontakte_l_schen.setText(QCoreApplication.translate("MainWindow", u"Kontakte l\u00f6schen", None))
        self.actionGlobale_Einstellungen.setText(QCoreApplication.translate("MainWindow", u"Globale Einstellungen", None))
        self.actionTAGs_Verwalten.setText(QCoreApplication.translate("MainWindow", u"TAGs-Verwalten", None))
        self.actionGruppen_Verwalten.setText(QCoreApplication.translate("MainWindow", u"Gruppen-Verwalten", None))
        self.actionHilfe.setText(QCoreApplication.translate("MainWindow", u"Hilfe", None))
        self.actionKontakt_hinzuf_gen.setText(QCoreApplication.translate("MainWindow", u"Kontakt hinzuf\u00fcgen", None))
        self.plainTextEditkontaktsuche.setPlainText(QCoreApplication.translate("MainWindow", u"Suche", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Kontakt hinzuf\u00fcgen", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Kontakt bearbeiten", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Kontakt l\u00f6schen", None))
        self.menuDatei.setTitle(QCoreApplication.translate("MainWindow", u"Datei", None))
        self.menuBearbeiten.setTitle(QCoreApplication.translate("MainWindow", u"Kontakte", None))
        self.menuEinstellungen.setTitle(QCoreApplication.translate("MainWindow", u"Einstellungen", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Nur wochenede Termine", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Montag Termine", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Dienstag Termine", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Mittwoch Termine", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Donnerstag Termine", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Freitag Termine", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Samstag Termine", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"Sonntag Termine", None))
        self.MENU.setItemText(self.MENU.indexOf(self.Einstellungenglobal), QCoreApplication.translate("MainWindow", u"Einstellungenglobal", None))
#if QT_CONFIG(tooltip)
        self.Kontakte.setToolTip(QCoreApplication.translate("MainWindow", u"Kontakteinstellungen", u"Kontakte"))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Kontakte.setStatusTip(QCoreApplication.translate("MainWindow", u"Kontakteinstellungen", u"Kontakte"))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.Kontakte.setWhatsThis(QCoreApplication.translate("MainWindow", u"Kontakte", u"Kontakte"))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Kontakte.setAccessibleName(QCoreApplication.translate("MainWindow", u"Kontakte", u"Kontakte"))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Kontakte.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Kontakte", u"Kontakte"))
#endif // QT_CONFIG(accessibility)
        self.Kontakte.setProperty(u"Kontakte", "")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Kontakt hinzuf\u00fcgen", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Kontakt bearbeiten", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Kontakt l\u00f6schen", None))
        self.MENU.setItemText(self.MENU.indexOf(self.Kontakte), QCoreApplication.translate("MainWindow", u"Kontakte", None))
#if QT_CONFIG(tooltip)
        self.TAGs.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>TAG's </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"TAG bearbeiten", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"TAG  hinzuf\u00fcgen", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"TAG l\u00f6schen", None))
        self.MENU.setItemText(self.MENU.indexOf(self.TAGs), QCoreApplication.translate("MainWindow", u"TAG's", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Gruppen bearbeiten", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Gruppen  hinzuf\u00fcgen", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Gruppen l\u00f6schen", None))
        self.MENU.setItemText(self.MENU.indexOf(self.Gruppen), QCoreApplication.translate("MainWindow", u"Gruppen", None))
    # retranslateUi